### ISSUE TITLE
issue with generator

### ISSUE THREAD

**Issue by ricky01-star** [halgari/HalgarisRPGLoot#2]
Loading Load Order
Found 437 activated mods
System.ArgumentException: Load order file had malformed line: {str}
   at Mutagen.Bethesda.LoadOrder.ProcessLoadOrder(Stream stream)
   at ClassBasedLootGenerator.Verbs.Generate.Execute()

**Comment by TwistedModding** [comment]
A bit late to the party by the looks of it, but I'm also having this issue.

**Comment by EzioTheDeadPoet** [comment]
The patcher works now check the updated instructions on the nexus mod page. 😊
